# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-04 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctorprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=264)),
                ('age', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('workinglocation', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('certificate', models.ImageField(blank=True, upload_to='profile_pics')),
                ('specialist', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofileinfo',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='DoctorProfileInfo',
        ),
    ]
