# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-04 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190304_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='certificate',
            field=models.ImageField(blank=True, upload_to='certificate_pics'),
        ),
    ]
