# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-07 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0005_auto_20190304_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofileinfo',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctorprofileinfo',
            name='doctor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
