# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-07 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0007_auto_20190307_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.PositiveIntegerField(default=10)),
                ('tuesday', models.PositiveIntegerField(default=10)),
                ('wednesday', models.PositiveIntegerField(default=10)),
                ('thursday', models.PositiveIntegerField(default=10)),
                ('friday', models.PositiveIntegerField(default=10)),
                ('saturday', models.PositiveIntegerField(default=10)),
                ('sunday', models.PositiveIntegerField(default=10)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
