# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-08 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfileInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hospitalname', models.CharField(max_length=200)),
                ('workinglocation', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('certificate', models.ImageField(blank=True, upload_to='certificate_pics')),
                ('specialist', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofileinfos',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='DoctorProfileInfos',
        ),
    ]
