# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20190308_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofileinfos',
            name='specialist',
            field=models.CharField(choices=[('General', 'General'), ('Orthologist', 'Orthologist'), ('Cardiologist', 'Cardiologist'), ('ENT', 'ENT'), ('Gastrologist', 'Gastrologist')], max_length=200),
        ),
    ]
