# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20190317_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorProfileInfos')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.UserProfileInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='availability',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
