# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-19 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20190319_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctortable',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='User',
        ),
        migrations.DeleteModel(
            name='DoctorTable',
        ),
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
