# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_auto_20190319_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofileinfos',
            name='specialist',
            field=models.CharField(choices=[('General', 'General'), ('Orthologist', 'Orthologist'), ('Cardiologist', 'Cardiologist'), ('Ent', 'Ent'), ('Gastrologist', 'Gastrologist')], max_length=200),
        ),
    ]
