# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-21 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0016_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppoinmentBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppoinmentBookedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('AppoinmentDate', models.DateTimeField()),
                ('BookedDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorProfileInfos')),
                ('Bookingperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
