# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-31 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_auto_20190331_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='Slot_No',
            field=models.IntegerField(default=1),
        ),
    ]
