# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-02 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_auto_20190401_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
